package com.roam.model.base;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Abstract base entity class providing common fields and behavior for all JPA
 * entities.
 * 
 * <p>
 * BaseEntity implements the common persistence patterns shared across all
 * domain entities
 * in the Roam application. It provides automatic ID generation, creation/update
 * timestamp
 * management, and consistent equals/hashCode/toString implementations.
 * </p>
 * 
 * <h2>Features:</h2>
 * <ul>
 * <li>Auto-generated primary key using database identity strategy</li>
 * <li>Automatic creation timestamp (immutable after persist)</li>
 * <li>Automatic update timestamp (refreshed on each update)</li>
 * <li>JPA lifecycle callbacks for timestamp automation</li>
 * <li>Consistent entity identity based on database ID</li>
 * <li>Stable hashCode implementation for pre-persistence entities</li>
 * </ul>
 * 
 * <h2>Usage:</h2>
 * 
 * <pre>{@code
 * @Entity
 * public class MyEntity extends BaseEntity {
 *     // Entity-specific fields and methods
 * }
 * }</pre>
 * 
 * @author Roam Development Team
 * @version 1.0
 * @since 1.0
 * @see jakarta.persistence.MappedSuperclass
 */
@MappedSuperclass
public abstract class BaseEntity {

    // ==================== Fields ====================

    /** Unique identifier generated by the database using identity strategy */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Timestamp when the entity was first persisted (immutable after creation) */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the most recent update to the entity */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ==================== Lifecycle Callbacks ====================

    /**
     * JPA lifecycle callback executed before entity insertion.
     * Initializes both creation and update timestamps to the current time.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback executed before entity update.
     * Refreshes the update timestamp to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ==================== Getters and Setters ====================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ==================== Object Methods ====================

    /**
     * Compares entities based on their database ID.
     * Two entities are equal if they have the same non-null ID.
     * 
     * @param o the object to compare
     * @return {@code true} if the entities have the same ID
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        BaseEntity that = (BaseEntity) o;
        return id != null && id.equals(that.id);
    }

    /**
     * Returns a stable hash code based on the entity class.
     * <p>
     * Uses class-based hashing to ensure hash code stability before and after
     * persistence, preventing issues when entities are stored in hash-based
     * collections before being assigned a database ID.
     * </p>
     * 
     * @return hash code based on the entity's class
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{id=" + id + "}";
    }
}
