package com.roam.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents a single task or action item within an Operation.
 * 
 * Tasks are the core units of work in Roam. They belong to an Operation
 * and can be connected to the calendar, wiki pages, and recur over time.
 * 
 * Key Features:
 * - Kanban support (TODO, IN_PROGRESS, DONE)
 * - Priority levels
 * - Recurring schedules (using iCalendar RRULE)
 * - Links to Calendar events and Wiki pages
 * 
 * @author Roam Development Team
 * @version 1.0
 */
@Entity
@Table(name = "tasks")
public class Task {

    /** Unique identifier for the task, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Reference to the parent Operation this task belongs to. Required field. */
    @Column(name = "operation_id", nullable = false)
    private Long operationId;

    /** Task title/name. Maximum 255 characters. Required field. */
    @Column(nullable = false, length = 255)
    private String title;

    /** Detailed description of the task. Supports long-form text content. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Current workflow status of the task (TODO, IN_PROGRESS, DONE). */
    @Enumerated(EnumType.STRING)
    @Column(length = 20, nullable = false)
    private TaskStatus status;

    /** Optional deadline for task completion. */
    @Column(name = "due_date")
    private LocalDateTime dueDate;

    /** Person or entity assigned to complete this task. */
    @Column(length = 100)
    private String assignee;

    /** Priority level affecting task ordering and visibility. */
    @Enumerated(EnumType.STRING)
    @Column(length = 10, nullable = false)
    private Priority priority;

    /** Order position for manual sorting within kanban columns. */
    @Column(nullable = false)
    private Integer position;

    /** Timestamp when the task was first created. Immutable after creation. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last modification. Auto-updated on save. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Life region category (e.g., Career, Finance, Health). */
    @Column(length = 50)
    private String region;

    /** Optional link to an associated calendar event. */
    @Column(name = "calendar_event_id")
    private Long calendarEventId;

    /** Optional link to an associated wiki page for notes/documentation. */
    @Column(name = "wiki_id")
    private Long wikiId;

    /** iCalendar RRULE format string for recurring tasks. */
    @Column(name = "recurrence_rule", columnDefinition = "TEXT")
    private String recurrenceRule;

    /**
     * End date for recurrence pattern, after which no new instances are created.
     */
    @Column(name = "recurrence_end_date")
    private LocalDateTime recurrenceEndDate;

    /** Reference to the parent task for recurring task instances. */
    @Column(name = "parent_task_id")
    private Long parentTaskId;

    /** Flag indicating if this task is a generated instance of a recurring task. */
    @Column(name = "is_recurring_instance", nullable = false)
    private Boolean isRecurringInstance = false;

    // ==================== Constructors ====================

    /**
     * Default constructor initializing task with sensible defaults.
     * Sets status to TODO, priority to MEDIUM, and position to 0.
     */
    public Task() {
        this.status = TaskStatus.TODO;
        this.priority = Priority.MEDIUM;
        this.position = 0;
    }

    /**
     * Convenience constructor for creating a task with title and operation.
     * 
     * @param title       the task title
     * @param operationId the parent operation ID
     */
    public Task(String title, Long operationId) {
        this();
        this.title = title;
        this.operationId = operationId;
    }

    // ==================== JPA Lifecycle Callbacks ====================

    /**
     * JPA callback executed before initial persistence.
     * Sets both created and updated timestamps to current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA callback executed before entity update.
     * Refreshes the updated timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ==================== Getters and Setters ====================
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOperationId() {
        return operationId;
    }

    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TaskStatus getStatus() {
        return status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    public LocalDateTime getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Long getCalendarEventId() {
        return calendarEventId;
    }

    public void setCalendarEventId(Long calendarEventId) {
        this.calendarEventId = calendarEventId;
    }

    public Long getWikiId() {
        return wikiId;
    }

    public void setWikiId(Long wikiId) {
        this.wikiId = wikiId;
    }

    public String getRecurrenceRule() {
        return recurrenceRule;
    }

    public void setRecurrenceRule(String recurrenceRule) {
        this.recurrenceRule = recurrenceRule;
    }

    public LocalDateTime getRecurrenceEndDate() {
        return recurrenceEndDate;
    }

    public void setRecurrenceEndDate(LocalDateTime recurrenceEndDate) {
        this.recurrenceEndDate = recurrenceEndDate;
    }

    public Long getParentTaskId() {
        return parentTaskId;
    }

    public void setParentTaskId(Long parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    public Boolean getIsRecurringInstance() {
        return isRecurringInstance;
    }

    public void setIsRecurringInstance(Boolean isRecurringInstance) {
        this.isRecurringInstance = isRecurringInstance;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Task task = (Task) o;
        return id != null && id.equals(task.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", status=" + status +
                ", priority=" + priority +
                ", dueDate=" + dueDate +
                ", assignee='" + assignee + '\'' +
                ", region='" + region + '\'' +
                ", calendarEventId=" + calendarEventId +
                ", wikiId=" + wikiId +
                ", recurrenceRule='" + recurrenceRule + '\'' +
                ", recurrenceEndDate=" + recurrenceEndDate +
                ", parentTaskId=" + parentTaskId +
                ", isRecurringInstance=" + isRecurringInstance +
                '}';
    }
}
